"""Central student-facing text catalog.

The goal of this module is to be the primary home for copy that is reused by
renderers and localization helpers. Keep visible wording here instead of adding
late patch blocks in feature modules.
"""

from __future__ import annotations

DESCRIPTOR_DISPLAY_NAMES: dict[str, dict[str, str]] = {
    "ru": {
        "MW": "Молекулярная масса",
        "LogP": "LogP",
        "TPSA": "TPSA",
        "HBD": "Доноры H-связей",
        "HBA": "Акцепторы H-связей",
        "RotatableBonds": "Вращаемые связи",
        "AromaticRings": "Ароматические кольца",
        "pKa_pred": "Предсказанный pKa",
        "FormalCharge": "Формальный заряд",
        "GasteigerMin": "Минимальный заряд Гастейгера",
        "GasteigerMax": "Максимальный заряд Гастейгера",
        "GasteigerAbsMax": "Максимальный |заряд Гастейгера|",
        "BBB_probability": "Оценка прохождения через ГЭБ",
        "Pgp_probability": "Оценка риска P-gp",
        "Clint_risk": "Риск Clint",
        "CATMoS_LD50": "CATMoS / LD50",
    },
    "kk": {
        "MW": "Молекулалық масса",
        "LogP": "LogP",
        "TPSA": "TPSA",
        "HBD": "Сутектік байланыс донорлары",
        "HBA": "Сутектік байланыс акцепторлары",
        "RotatableBonds": "Айналмалы байланыстар",
        "AromaticRings": "Ароматты сақиналар",
        "pKa_pred": "Болжанған pKa",
        "FormalCharge": "Формальды заряд",
        "GasteigerMin": "Гастейгердің ең төмен заряды",
        "GasteigerMax": "Гастейгердің ең жоғары заряды",
        "GasteigerAbsMax": "Ең үлкен |Гастейгер заряды|",
        "BBB_probability": "Қан-ми тосқауылынан өту бағасы",
        "Pgp_probability": "P-gp қаупінің бағасы",
        "Clint_risk": "Clint қаупі",
        "CATMoS_LD50": "CATMoS / LD50",
    },
    "en": {
        "MW": "Molecular weight",
        "LogP": "LogP",
        "TPSA": "TPSA",
        "HBD": "Hydrogen-bond donors",
        "HBA": "Hydrogen-bond acceptors",
        "RotatableBonds": "Rotatable bonds",
        "AromaticRings": "Aromatic rings",
        "pKa_pred": "Predicted pKa",
        "FormalCharge": "Formal charge",
        "GasteigerMin": "Minimum Gasteiger charge",
        "GasteigerMax": "Maximum Gasteiger charge",
        "GasteigerAbsMax": "Maximum |Gasteiger charge|",
        "BBB_probability": "BBB passage estimate",
        "Pgp_probability": "P-gp risk estimate",
        "Clint_risk": "Clint risk",
        "CATMoS_LD50": "CATMoS / LD50",
    },
}

DESCRIPTOR_SHORT_LABELS: dict[str, dict[str, str]] = {
    "ru": {
        "MW": "MW",
        "LogP": "LogP",
        "TPSA": "TPSA",
        "HBD": "HBD",
        "HBA": "HBA",
        "RotatableBonds": "RotB",
        "AromaticRings": "Ароматические кольца",
        "pKa_pred": "pKa",
        "FormalCharge": "Заряд",
        "GasteigerMin": "Gasteiger min",
        "GasteigerMax": "Gasteiger max",
        "GasteigerAbsMax": "|Gasteiger|max",
        "BBB_probability": "ГЭБ",
        "Pgp_probability": "P-gp",
        "Clint_risk": "Clint",
        "CATMoS_LD50": "LD50",
    },
    "kk": {
        "MW": "MW",
        "LogP": "LogP",
        "TPSA": "TPSA",
        "HBD": "HBD",
        "HBA": "HBA",
        "RotatableBonds": "RotB",
        "AromaticRings": "Ароматты сақиналар",
        "pKa_pred": "pKa",
        "FormalCharge": "Заряд",
        "GasteigerMin": "Gasteiger min",
        "GasteigerMax": "Gasteiger max",
        "GasteigerAbsMax": "|Gasteiger|max",
        "BBB_probability": "Қан-ми тосқауылы",
        "Pgp_probability": "P-gp",
        "Clint_risk": "Clint",
        "CATMoS_LD50": "LD50",
    },
    "en": {
        "MW": "MW",
        "LogP": "LogP",
        "TPSA": "TPSA",
        "HBD": "HBD",
        "HBA": "HBA",
        "RotatableBonds": "RotB",
        "AromaticRings": "Aromatic rings",
        "pKa_pred": "pKa",
        "FormalCharge": "Charge",
        "GasteigerMin": "Gasteiger min",
        "GasteigerMax": "Gasteiger max",
        "GasteigerAbsMax": "|Gasteiger|max",
        "BBB_probability": "BBB",
        "Pgp_probability": "P-gp",
        "Clint_risk": "Clint",
        "CATMoS_LD50": "LD50",
    },
}

DESCRIPTOR_THRESHOLD_NOTES: dict[str, dict[str, str]] = {
    "ru": {
        "MW": "Учебная эвристика: 150-450 Da обычно благоприятнее для профиля ЦНС-доступности.",
        "LogP": "Учебная эвристика: умеренный LogP примерно 1.5-3.5 поддерживает пассивную диффузию.",
        "TPSA": "Учебная эвристика: TPSA <= 70 Å² обычно благоприятнее для прохождения через ГЭБ; > 90 Å² часто неблагоприятно.",
        "HBD": "Учебная эвристика: 0-1 HBD обычно благоприятно; >= 3 часто мешает пассивному прохождению через ГЭБ.",
        "HBA": "Учебная эвристика: 0-5 HBA обычно допустимо; >= 8 часто неблагоприятно.",
        "RotatableBonds": "Учебная эвристика: 0-5 вращаемых связей обычно лучше; > 8 указывает на высокую гибкость.",
        "AromaticRings": "Учебная эвристика: умеренное число ароматических колец допустимо; избыток может повышать липофильность и связывание.",
        "pKa_pred": "Интерпретация pKa зависит от кислотно-основного центра; pKa около 7.4 требует осторожности.",
        "FormalCharge": "Учебная эвристика: нейтральная форма обычно благоприятнее для пассивного прохождения через ГЭБ.",
        "GasteigerMin": "Частичные заряды следует интерпретировать вместе с TPSA, HBD/HBA и формальным зарядом.",
        "GasteigerMax": "Частичные заряды следует интерпретировать вместе с TPSA, HBD/HBA и формальным зарядом.",
        "GasteigerAbsMax": "Высокий локальный заряд может указывать на выраженную полярность.",
        "BBB_probability": "Вероятность модели - это расчётная оценка in silico, а не экспериментальная вероятность.",
        "Pgp_probability": "Высокая оценка P-gp указывает на риск активного выведения, а не на низкую пассивную проницаемость саму по себе.",
        "Clint_risk": "Clint описывает метаболическую стабильность/клиренс и дополняет, но не заменяет анализ прохождения через ГЭБ.",
        "CATMoS_LD50": "Токсикологический прогноз следует трактовать отдельно от оценки прохождения через ГЭБ.",
    },
    "kk": {
        "MW": "Оқу эвристикасы: 150-450 Da аралығы ОЖЖ қолжетімділігі профилі үшін жиі қолайлырақ.",
        "LogP": "Оқу эвристикасы: шамамен 1.5-3.5 аралығындағы орташа LogP пассивті диффузияны қолдайды.",
        "TPSA": "Оқу эвристикасы: TPSA <= 70 Å² қан-ми тосқауылынан өту үшін жиі қолайлы; > 90 Å² жиі қолайсыз.",
        "HBD": "Оқу эвристикасы: 0-1 HBD әдетте қолайлы; >= 3 қан-ми тосқауылынан пассивті өтуге кедергі келтіруі мүмкін.",
        "HBA": "Оқу эвристикасы: 0-5 HBA әдетте қолайлы; >= 8 жиі қолайсыз.",
        "RotatableBonds": "Оқу эвристикасы: 0-5 айналмалы байланыс әдетте жақсырақ; > 8 жоғары икемділікті көрсетеді.",
        "AromaticRings": "Оқу эвристикасы: ароматты сақиналардың орташа саны қолайлы; артық саны липофильділік пен байланысуды арттыруы мүмкін.",
        "pKa_pred": "pKa түсіндірмесі қышқыл-негіз орталығына тәуелді; 7.4 маңындағы pKa сақтықты қажет етеді.",
        "FormalCharge": "Оқу эвристикасы: бейтарап түр қан-ми тосқауылынан пассивті өту үшін әдетте қолайлырақ.",
        "GasteigerMin": "Жартылай зарядтарды TPSA, HBD/HBA және формальды зарядпен бірге түсіндіру керек.",
        "GasteigerMax": "Жартылай зарядтарды TPSA, HBD/HBA және формальды зарядпен бірге түсіндіру керек.",
        "GasteigerAbsMax": "Жоғары жергілікті заряд айқын полярлықты көрсетуі мүмкін.",
        "BBB_probability": "Модель бағасы есептік көрсеткіш болып табылады; ол эксперименттік ықтималдық емес.",
        "Pgp_probability": "Жоғары P-gp бағасы белсенді шығарылу қаупін көрсетеді; бұл пассивті өтудің өзі міндетті түрде төмен деген сөз емес.",
        "Clint_risk": "Clint метаболикалық тұрақтылық/клиренсті сипаттайды және қан-ми тосқауылынан өтуді талдауды толықтырады, бірақ алмастырмайды.",
        "CATMoS_LD50": "Токсикологиялық болжам қан-ми тосқауылынан өтуді бағалаудан бөлек түсіндірілуі керек.",
    },
    "en": {
        "MW": "Educational heuristic: 150-450 Da is often more favourable for a CNS profile.",
        "LogP": "Educational heuristic: moderate LogP around 1.5-3.5 supports passive diffusion.",
        "TPSA": "Educational heuristic: TPSA <= 70 Å² is often favourable for BBB; > 90 Å² is often unfavourable.",
        "HBD": "Educational heuristic: 0-1 HBD is usually favourable; >= 3 often opposes passive BBB diffusion.",
        "HBA": "Educational heuristic: 0-5 HBA is often acceptable; >= 8 is often unfavourable.",
        "RotatableBonds": "Educational heuristic: 0-5 rotatable bonds is usually better; > 8 suggests high flexibility.",
        "AromaticRings": "Educational heuristic: a moderate number of aromatic rings can be acceptable; excess aromaticity may increase lipophilicity and binding.",
        "pKa_pred": "pKa interpretation depends on the acid/base centre; pKa near 7.4 requires caution.",
        "FormalCharge": "Educational heuristic: a neutral form is usually more favourable for passive BBB diffusion.",
        "GasteigerMin": "Partial charges should be interpreted together with TPSA, HBD/HBA and formal charge.",
        "GasteigerMax": "Partial charges should be interpreted together with TPSA, HBD/HBA and formal charge.",
        "GasteigerAbsMax": "High local charge may indicate pronounced polarity.",
        "BBB_probability": "The model score is an in silico score, not an experimental probability.",
        "Pgp_probability": "A high P-gp score indicates active efflux risk, not low passive permeability by itself.",
        "Clint_risk": "Clint describes metabolic stability/clearance and complements, but does not replace, BBB analysis.",
        "CATMoS_LD50": "The toxicology estimate should be interpreted separately from BBB permeability.",
    },
}

ZONE_COMMENTS: dict[str, dict[str, dict[str, str]]] = {
    "ru": {
        "MW": {
            "green": "Значение находится в учебно благоприятном диапазоне для прохождения через ГЭБ.",
            "yellow": "Значение пограничное: само по себе не блокирует прохождение через ГЭБ, но требует контекстной оценки.",
            "red": "Значение может ухудшать пассивное прохождение через ГЭБ.",
            "gray": "Влияние размера на прохождение через ГЭБ не удалось оценить по доступным данным.",
        },
        "LogP": {
            "green": "Липофильность выглядит умеренной и поддерживает пассивную диффузию.",
            "yellow": "Липофильность пограничная: возможен компромисс между прохождением через мембрану и растворимостью.",
            "red": "Липофильность выглядит неблагоприятной: молекула может быть слишком гидрофильной или слишком липофильной.",
            "gray": "Влияние LogP не удалось оценить по доступным данным.",
        },
        "TPSA": {
            "green": "Полярная поверхность низкая или умеренная, что поддерживает пассивное прохождение через ГЭБ.",
            "yellow": "TPSA находится в пограничной зоне: фактор может снижать уверенность в прохождении через ГЭБ.",
            "red": "Высокая TPSA обычно препятствует пассивному прохождению через липидный барьер.",
            "gray": "Влияние TPSA не удалось оценить по доступным данным.",
        },
        "HBD": {
            "green": "Низкое число доноров водородных связей благоприятно для прохождения через ГЭБ.",
            "yellow": "Число доноров водородных связей пограничное.",
            "red": "Повышенное число HBD может мешать пассивной диффузии через ГЭБ.",
            "gray": "Влияние HBD не удалось оценить по доступным данным.",
        },
        "HBA": {
            "green": "Число акцепторов водородных связей выглядит допустимым для прохождения через ГЭБ.",
            "yellow": "Число HBA пограничное и может повышать полярность.",
            "red": "Высокое число HBA может снижать пассивное прохождение через ГЭБ.",
            "gray": "Влияние HBA не удалось оценить по доступным данным.",
        },
        "Pgp_probability": {
            "green": "Низкий риск активного выведения через P-gp поддерживает доступность для ЦНС.",
            "yellow": "Оценка P-gp находится в зоне неопределённости.",
            "red": "Высокий риск активного выведения через P-gp может снижать фактическую доступность в ЦНС.",
            "gray": "Оценка P-gp недоступна.",
        },
        "BBB_probability": {
            "green": "Модель относит молекулу к зоне высокой оценки прохождения через ГЭБ.",
            "yellow": "Вероятность близка к переходной зоне; вывод лучше считать пограничным.",
            "red": "Модель относит молекулу к зоне низкой оценки прохождения через ГЭБ.",
            "gray": "Оценка прохождения через ГЭБ недоступна.",
        },
    },
    "kk": {
        "MW": {
            "green": "Мән қан-ми тосқауылынан өту үшін қолайлы оқу диапазонында.",
            "yellow": "Мән шекаралық: жеке өзі қан-ми тосқауылынан өтуді жоққа шығармайды, бірақ контекст қажет.",
            "red": "Мән қан-ми тосқауылынан пассивті өтуді нашарлатуы мүмкін.",
            "gray": "Өлшем әсерін қолда бар дерекпен бағалау қиын.",
        },
        "LogP": {
            "green": "Липофильділік орташа және пассивті диффузияны қолдайды.",
            "yellow": "Липофильділік шекаралық: мембранадан өту мен ерігіштік арасында компромисс болуы мүмкін.",
            "red": "Липофильділік қолайсыз: молекула тым гидрофильді немесе тым липофильді болуы мүмкін.",
            "gray": "LogP әсерін бағалау мүмкін емес.",
        },
        "TPSA": {
            "green": "Полярлық беткей төмен немесе орташа, бұл қан-ми тосқауылынан пассивті өтуді қолдайды.",
            "yellow": "TPSA шекаралық аймақта; қан-ми тосқауылынан өту туралы сенімділік төмендеуі мүмкін.",
            "red": "Жоғары TPSA липидті бөгеттен пассивті өтуді әдетте қиындатады.",
            "gray": "TPSA әсерін бағалау мүмкін емес.",
        },
        "HBD": {
            "green": "Сутектік байланыс донорларының саны аз; бұл қан-ми тосқауылынан өту үшін қолайлы.",
            "yellow": "Сутектік байланыс донорларының саны шекаралық.",
            "red": "Сутектік байланыс донорлары көп болса, қан-ми тосқауылынан пассивті өтуге кедергі келтіруі мүмкін.",
            "gray": "HBD әсерін бағалау мүмкін емес.",
        },
        "HBA": {
            "green": "Сутектік байланыс акцепторларының саны қан-ми тосқауылынан өту үшін қолайлы көрінеді.",
            "yellow": "Сутектік байланыс акцепторларының саны шекаралық және полярлықты арттыруы мүмкін.",
            "red": "Сутектік байланыс акцепторлары көп болса, қан-ми тосқауылынан пассивті өту төмендеуі мүмкін.",
            "gray": "HBA әсерін бағалау мүмкін емес.",
        },
        "RotatableBonds": {
            "green": "Икемділік төмен немесе орташа, бұл профиль үшін қолайлы.",
            "yellow": "Икемділік шекаралық аймақта; қосымша контекст қажет.",
            "red": "Жоғары икемділік пассивті өту мен ADMET болжамын қиындатуы мүмкін.",
            "gray": "Икемділік әсерін бағалау мүмкін емес.",
        },
        "AromaticRings": {
            "green": "Ароматты сақиналардың саны қалыпты және профильге қарсы айқын белгі бермейді.",
            "yellow": "Ароматтылық шекаралық: липофильділік пен ақуыздармен байланысу өсуі мүмкін.",
            "red": "Ароматтылық жоғары; липофильділік пен ақуыздармен байланысу артуы мүмкін.",
            "gray": "Ароматтылық әсерін бағалау мүмкін емес.",
        },
        "pKa_pred": {
            "green": "pKa 7.4 pH-та айқын иондануды көрсетпейді.",
            "yellow": "pKa физиологиялық pH-қа жақын немесе орталықтың қышқыл/негіз типін білуді қажет етеді.",
            "red": "pKa физиологиялық pH-та көбіне иондалған түрге нұсқауы мүмкін.",
            "gray": "pKa түсіндірмесі қышқыл-негіз орталығына тәуелді.",
        },
        "FormalCharge": {
            "green": "Формальды заряд жоқ, бұл пассивті диффузия үшін қолайлы.",
            "yellow": "Формальды заряд бар; қан-ми тосқауылынан пассивті өту төмендеуі мүмкін.",
            "red": "Айқын формальды заряд қан-ми тосқауылынан пассивті өтуді қатты шектеуі мүмкін.",
            "gray": "Формальды заряд әсерін бағалау мүмкін емес.",
        },
        "BBB_probability": {
            "green": "Қан-ми тосқауылынан өту бағасы жоғары аймақта.",
            "yellow": "Қан-ми тосқауылынан өту бағасы шекаралық аймақта.",
            "red": "Қан-ми тосқауылынан өту бағасы төмен аймақта.",
            "gray": "Қан-ми тосқауылынан өту бағасы қолжетімсіз.",
        },
        "Pgp_probability": {
            "green": "P-gp арқылы белсенді шығарылу қаупі төмен, ОЖЖ қолжетімділігі үшін қолайлы.",
            "yellow": "P-gp бағасы анық емес аймақта.",
            "red": "P-gp арқылы белсенді шығарылу қаупі жоғары, ОЖЖ қолжетімділігін төмендетуі мүмкін.",
            "gray": "P-gp бағасы қолжетімсіз.",
        },
    },
    "en": {
        "BBB_probability": {
            "green": "The BBB passage estimate is in the high range.",
            "yellow": "The BBB passage estimate is borderline.",
            "red": "The BBB passage estimate is in the low range.",
            "gray": "BBB passage estimate is unavailable.",
        },
        "Pgp_probability": {
            "green": "Low P-gp active-removal risk supports CNS exposure.",
            "yellow": "P-gp estimate is in the uncertainty zone.",
            "red": "High P-gp active-removal risk may reduce actual CNS exposure.",
            "gray": "P-gp estimate is unavailable.",
        },
    },
}
